version: '3.8'
services:
  # Kafka setup (zookeeper is a dependency)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ordering-net
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - ordering-net

  # PostgreSQL databases for each microservice
  orders_db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${ORDERS_POSTGRES_DB}
      POSTGRES_USER: ${ORDERS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDERS_POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    networks:
      - ordering-net
  products_db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - products_db_data:/var/lib/postgresql/data
    networks:
      - ordering-net
  # Node.js Order Service container
  order-service:
    build: ./order-service
    depends_on:
      - orders_db
      - kafka
    restart: unless-stopped
    environment:
      # Inject environment variables for the database connection
      DB_HOST: orders_db
      DB_USER: ${ORDERS_POSTGRES_USER}
      DB_PASSWORD: ${ORDERS_POSTGRES_PASSWORD}
      DB_NAME: ${ORDERS_POSTGRES_DB}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL}
    ports:
      - "3001:3001"
    networks:
      - ordering-net
  # Node.js Product Service container
  product-service:
    build: ./product-service
    depends_on:
      - products_db
      - kafka
    restart: unless-stopped
    environment:
      # Inject environment variables for the database connection
      DB_HOST: products_db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    ports:
      - "3002:3002"
    networks:
      - ordering-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 5
  # React Frontend container
  my-ordering-app:
    build: ./my-ordering-app
    depends_on:
      - order-service
      - product-service
    ports:
      - "3000:3000" # Expose the port to your host machine
    environment:
      REACT_APP_ORDER_SERVICE_URL: http://localhost:3001
      #REACT_APP_ORDER_SERVICE_URL: http://order-service:3001
      REACT_APP_PRODUCT_SERVICE_URL: http://localhost:3002
    networks:
      - ordering-net

volumes:
  products_db_data:
  orders_db_data:

networks:
  ordering-net:
    driver: bridge
